[2022-12-04 03:11:19,616] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-10-27T12:30:00+00:00 [queued]>
[2022-12-04 03:11:19,700] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag1.get_data scheduled__2022-10-27T12:30:00+00:00 [queued]>
[2022-12-04 03:11:19,702] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 03:11:19,704] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 03:11:19,704] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 03:11:19,782] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_data> on 2022-10-27 12:30:00+00:00
[2022-12-04 03:11:19,790] {standard_task_runner.py:52} INFO - Started process 1817 to run task
[2022-12-04 03:11:19,813] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'get_data', 'scheduled__2022-10-27T12:30:00+00:00', '--job-id', '883', '--raw', '--subdir', 'DAGS_FOLDER/AirflowClean2.py', '--cfg-path', '/tmp/tmp2wvjq5ye', '--error-file', '/tmp/tmp1dje3zud']
[2022-12-04 03:11:19,825] {standard_task_runner.py:77} INFO - Job 883: Subtask get_data
[2022-12-04 03:11:20,200] {logging_mixin.py:109} INFO - Running <TaskInstance: dag1.get_data scheduled__2022-10-27T12:30:00+00:00 [running]> on host 422c372562ce
[2022-12-04 03:11:20,635] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Fadlil
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T12:30:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-27T12:30:00+00:00
[2022-12-04 03:11:21,724] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 03:11:21,800] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dag1, task_id=get_data, execution_date=20221027T123000, start_date=20221204T031119, end_date=20221204T031121
[2022-12-04 03:11:22,109] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 03:11:22,542] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
